# Generated by Django 5.2.6 on 2025-10-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('association_type', models.CharField(choices=[('batch', 'Batch'), ('bag', 'Bag'), ('standalone', 'Standalone')], default='standalone', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=100)),
                ('production_type', models.CharField(max_length=100)),
                ('production_date', models.DateTimeField()),
                ('form_gate_sourced', models.BooleanField(default=False)),
                ('cluser_group', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('uoms', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('working', 'Working'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, limit_choices_to={'association_type': 'batch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.form')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('bag_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_lot_number', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=100)),
                ('external_lot_number', models.CharField(max_length=100)),
                ('external_update_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('working', 'Working'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('form', models.ForeignKey(blank=True, limit_choices_to={'association_type': 'bag'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.form')),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('form_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('email', 'Email'), ('url', 'URL')], max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.form')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
