# Generated by Django 5.2.6 on 2025-10-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bag_form_data_alter_batch_form_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
