# Generated by Django 5.2.6 on 2025-10-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_submission_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='cluser_group',
            new_name='cluster_group',
        ),
    ]
